version: '3'

services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html'
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  mysql:
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pizza
      - MYSQL_TCP_PORT=3306
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
