version: '3'

services:
  php:
    container_name: php
    build:
      dockerfile: docker/php/Dockerfile
    volumes:
      - './src:/var/www/html'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  mysql:
    container_name: mysql
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=pizza
      - MYSQL_TCP_PORT=3306
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'
      - './docker/volume/init.sql:/docker-entrypoint-initdb.d/init.sql'

#  pgsql:
#    image: postgres:latest
#    container_name: pgsql
#    environment:
#        POSTGRES_USER: test_user
#        POSTGRES_PASSWORD: test_password
#        POSTGRES_DB: test_database
#    ports:
#        - "5433:5432"
#    volumes:
#        - ./docker/volume/test_db_data:/var/lib/postgresql/data


  phpmyadmin:
    container_name: phpadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "9090:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql

#  redis:
#    container_name: redis
#    image: redis:alpine
#    ports:
#      - "6379:6379"
